# A string used to distinguish different Supabase projects on the same host. Defaults to the
# working directory name when running `supabase init`.
project_id = "booth-tracker"

[api]
# Port to use for the API URL.
port = 54321
# Schemas to expose in your API. Tables, views and stored procedures in this schema will get API endpoints.
# public and storage are always included.
schemas = ["public", "storage", "graphql_public"]
# Extra schemas to add to the search_path of every request. public is always included.
extra_search_path = ["public", "extensions"]
# The maximum number of rows returned from a table or view. Limits payload size for accidental or malicious requests.
max_rows = 1000

[db]
# Port to use for the local database URL.
port = 54322
# Port used by db diff command to initialize the shadow database.
shadow_port = 54320
# The database major version to use. This has to be the same as your remote database's. Run `SHOW server_version;` on the remote database to check.
major_version = 15

[db.pooler]
# Port to use for the local connection pooler.
port = 54329
# Specifies when a server connection can be reused by other clients.
# Configure one of the supported pooler modes: `transaction`, `session`.
pool_mode = "transaction"
# How many server connections to allow per user/database pair.
default_pool_size = 15
# Maximum number of client connections allowed.
max_client_conn = 100

[realtime]
# Bind realtime via either IPv4 or IPv6. (default: IPv4)
# ip_version = "IPv4"

[studio]
# Port to use for Supabase Studio.
port = 54323
# External URL of the API server that frontend connects to.
api_url = "http://127.0.0.1:54321"

# Email testing server. Emails sent with the local dev setup are not actually sent - rather, they
# are monitored, and you can view the emails that would have been sent from the web interface.
[inbucket]
# Port to use for the email testing server web interface.
port = 54324
# Uncomment to expose additional ports for testing user applications that send emails.
# smtp_port = 2500
# pop3_port = 1100

[storage]
# The maximum file size allowed (e.g. "5MB", "500KB").
file_size_limit = "50MiB"

[auth]
# The base URL of your website. Used as an allow-list for redirects and for constructing URLs used
# in emails.
site_url = "http://localhost:3000"
# A list of *exact* URLs that auth providers are permitted to redirect to post authentication.
additional_redirect_urls = ["https://localhost:3000"]
# How long tokens are valid for, in seconds. Defaults to 3600 (1 hour), maximum 604800 (1 week).
jwt_expiry = 3600
# If disabled, the refresh token will never expire.
enable_refresh_token_rotation = true
# Allows refresh tokens to be reused after expiry, up to the specified interval in seconds.
# Requires enable_refresh_token_rotation = true.
refresh_token_reuse_interval = 10
# Allow/disallow new user signups to your project.
enable_signup = true

[auth.email]
# Allow/disallow new user signups via email to your project.
enable_signup = true
# If enabled, a user will be required to confirm any email change on both the old, and new email addresses. If disabled, only the new email is required to confirm.
double_confirm_changes = true
# If enabled, users need to confirm their email address before signing in.
enable_confirmations = false

# Uncomment to customize email template
# [auth.email.template.invite]
# subject = "You have been invited"
# content_path = "./supabase/templates/invite.html"

# Uncomment to customize email template
# [auth.email.template.confirmation]
# subject = "Confirm your signup"
# content_path = "./supabase/templates/confirmation.html"

# Uncomment to customize email template
# [auth.email.template.recovery]
# subject = "Reset your password"
# content_path = "./supabase/templates/recovery.html"

# Uncomment to customize email template
# [auth.email.template.email_change]
# subject = "Confirm your email change"
# content_path = "./supabase/templates/email_change.html"

# Uncomment to customize email template
# [auth.email.template.magic_link]
# subject = "Your magic link"
# content_path = "./supabase/templates/magic_link.html"

[auth.sms]
# Allow/disallow new user signups via SMS to your project.
enable_signup = true
# If enabled, users need to confirm their phone number before signing in.
enable_confirmations = false
# Template for sending a confirmation message to the user's phone number.
template = "Your code is {{ .Code }}"

[auth.external.apple]
# Apple OAuth provider is disabled by default.
enabled = false
# OAuth client ID from Apple.
client_id = ""
# OAuth client secret from Apple.
secret = ""
# Overrides the default auth redirectUrl.
redirect_uri = ""
# Overrides the default auth provider URL. Used to support self-hosted gitlab, single-tenant Azure,
# or any other third-party OIDC providers.
url = ""

[auth.external.azure]
# Azure AD OAuth provider is disabled by default.
enabled = false
# OAuth client ID from Azure AD.
client_id = ""
# OAuth client secret from Azure AD.
secret = ""
# Overrides the default auth redirectUrl.
redirect_uri = ""
# Overrides the default auth provider URL. Used to support self-hosted gitlab, single-tenant Azure,
# or any other third-party OIDC providers.
url = ""

[auth.external.bitbucket]
# Bitbucket OAuth provider is disabled by default.
enabled = false
# OAuth client ID from Bitbucket.
client_id = ""
# OAuth client secret from Bitbucket.
secret = ""
# Overrides the default auth redirectUrl.
redirect_uri = ""

[auth.external.discord]
# Discord OAuth provider is disabled by default.
enabled = false
# OAuth client ID from Discord.
client_id = ""
# OAuth client secret from Discord.
secret = ""
# Overrides the default auth redirectUrl.
redirect_uri = ""

[auth.external.facebook]
# Facebook OAuth provider is disabled by default.
enabled = false
# OAuth client ID from Facebook.
client_id = ""
# OAuth client secret from Facebook.
secret = ""
# Overrides the default auth redirectUrl.
redirect_uri = ""

[auth.external.github]
# GitHub OAuth provider is disabled by default.
enabled = false
# OAuth client ID from GitHub.
client_id = ""
# OAuth client secret from GitHub.
secret = ""
# Overrides the default auth redirectUrl.
redirect_uri = ""

[auth.external.gitlab]
# GitLab OAuth provider is disabled by default.
enabled = false
# OAuth client ID from GitLab.
client_id = ""
# OAuth client secret from GitLab.
secret = ""
# Overrides the default auth redirectUrl.
redirect_uri = ""
# Overrides the default auth provider URL. Used to support self-hosted gitlab, single-tenant Azure,
# or any other third-party OIDC providers.
url = ""

[auth.external.google]
# Google OAuth provider is disabled by default.
enabled = false
# OAuth client ID from Google.
client_id = ""
# OAuth client secret from Google.
secret = ""
# Overrides the default auth redirectUrl.
redirect_uri = ""

[auth.external.keycloak]
# Keycloak OAuth provider is disabled by default.
enabled = false
# OAuth client ID from Keycloak.
client_id = ""
# OAuth client secret from Keycloak.
secret = ""
# Overrides the default auth redirectUrl.
redirect_uri = ""
# Overrides the default auth provider URL. Used to support self-hosted gitlab, single-tenant Azure,
# or any other third-party OIDC providers.
url = ""

[auth.external.linkedin]
# LinkedIn OAuth provider is disabled by default.
enabled = false
# OAuth client ID from LinkedIn.
client_id = ""
# OAuth client secret from LinkedIn.
secret = ""
# Overrides the default auth redirectUrl.
redirect_uri = ""

[auth.external.notion]
# Notion OAuth provider is disabled by default.
enabled = false
# OAuth client ID from Notion.
client_id = ""
# OAuth client secret from Notion.
secret = ""
# Overrides the default auth redirectUrl.
redirect_uri = ""

[auth.external.slack]
# Slack OAuth provider is disabled by default.
enabled = false
# OAuth client ID from Slack.
client_id = ""
# OAuth client secret from Slack.
secret = ""
# Overrides the default auth redirectUrl.
redirect_uri = ""

[auth.external.spotify]
# Spotify OAuth provider is disabled by default.
enabled = false
# OAuth client ID from Spotify.
client_id = ""
# OAuth client secret from Spotify.
secret = ""
# Overrides the default auth redirectUrl.
redirect_uri = ""

[auth.external.twitch]
# Twitch OAuth provider is disabled by default.
enabled = false
# OAuth client ID from Twitch.
client_id = ""
# OAuth client secret from Twitch.
secret = ""
# Overrides the default auth redirectUrl.
redirect_uri = ""

[auth.external.twitter]
# Twitter OAuth provider is disabled by default.
enabled = false
# OAuth client ID from Twitter.
client_id = ""
# OAuth client secret from Twitter.
secret = ""
# Overrides the default auth redirectUrl.
redirect_uri = ""

[auth.external.workos]
# WorkOS SAML provider is disabled by default.
enabled = false
# WorkOS API key.
secret = ""
# Overrides the default auth redirectUrl.
redirect_uri = ""

[auth.external.zoom]
# Zoom OAuth provider is disabled by default.
enabled = false
# OAuth client ID from Zoom.
client_id = ""
# OAuth client secret from Zoom.
secret = ""
# Overrides the default auth redirectUrl.
redirect_uri = ""

[functions.registerBooth]
enabled = true
verify_jwt = true
import_map = "./functions/registerBooth/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/registerBooth/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/registerBooth/*.html" ]

[functions.getBooths]
enabled = true
verify_jwt = true
import_map = "./functions/getBooths/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/getBooths/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/getBooths/*.html" ]

[functions.updateBoothPhrase]
enabled = true
verify_jwt = true
import_map = "./functions/updateBoothPhrase/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/updateBoothPhrase/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/updateBoothPhrase/*.html" ]

[functions.updateBooth]
enabled = true
verify_jwt = true
import_map = "./functions/updateBooth/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/updateBooth/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/updateBooth/*.html" ]

[functions.visitBooth]
enabled = true
verify_jwt = true
import_map = "./functions/visitBooth/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/visitBooth/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/visitBooth/*.html" ]

[functions.deleteBooth]
enabled = true
verify_jwt = true
import_map = "./functions/deleteBooth/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/deleteBooth/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/deleteBooth/*.html" ]

[functions.deleteUser]
enabled = true
verify_jwt = true
import_map = "./functions/deleteUser/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/deleteUser/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/deleteUser/*.html" ]

[functions.getUserProgress]
enabled = true
verify_jwt = true
import_map = "./functions/getUserProgress/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/getUserProgress/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/getUserProgress/*.html" ]
